### PR TITLE
Log formatting, replyes formatting

### PR DESCRIPTION
**Pull request by andyzasl**
:)
less text on logs

### CODE REVIEW

**Comment by emptywee** [comment]
Looks okay, but if you have decided to put chatroom's name into logs, I think it should be placed to the access/denied messages as well, so that you can track it thru the logs better.

**Comment by andyzasl** [comment]
It was there already, I just deleted extra strings.

**Comment by emptywee** [comment]
@andyzasl yeah, but you have merged it into one line (see L18). Could you add room name into other log entries so the PR looks complete, and I'll merge it ? Thanks

**Comment by andyzasl** [comment]
Take a look again :)

**Comment by emptywee** [comment]
Ok, looks good to me. Thanks :)

**Pull request merged**
